task/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


    Route::get('/', 'Front\HomeController@showposts');
    Route::get('/pages', 'Front\HomeController@showpages')->name('pages');
    Route::get('/pagesdetails/{post}', 'Front\HomeController@showpages')->name('pagesdetails');

Route::group([
    'prefix' => '/admin',
    'as' => 'admin.',
    'middleware' => ['auth' ]
], function () {
Route::get('/', 'DashboardController')->name('dashboard');
     

//route users
Route::group([
    'prefix' => 'users',
    'as' => 'users.'
], function () {
    Route::get('/get-users', 'UserController@getUsers')->name('get-users');
});
Route::resource('/users', 'UserController');

//route posts

Route::group([
    'prefix' => 'posts',
    'as' => 'posts.'
], function () {
    Route::get('/get-posts', 'PostController@getPosts')->name('get-posts');
});
Route::resource('/posts', 'PostController');

//route pages

Route::group([
    'prefix' => 'pages',
    'as' => 'pages.'
], function () {
    Route::get('/get-pages', 'PageController@getPages')->name('get-pages');
});
Route::resource('/pages', 'PageController');

});




Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

task/resources/views/admin/page/create.blade.php
@extends('layouts.app')

@section('title', 'All Pages')

@section('content')
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0 text-dark">pages</h1>
                    </div><!-- /.col -->
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="/">admin</a></li>
                            <li class="breadcrumb-item"><a href="{{ route('admin.pages.index') }}">pages</a></li>
                            <li class="breadcrumb-item active">Create new page</li>
                        </ol>
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->

        <!-- Main content -->
        <div class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="card card-body">
                        <form action="{{ route('admin.pages.store') }}" method="post">
                           @include('admin.page.form')
                        </form>

                    </div>
                </div>
                <!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content -->
    </div>
@endsection

task/resources/views/admin/page/edit.blade.php
@extends('layouts.app')

@section('title', 'All Pages')

@section('content')
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0 text-dark">Pages</h1>
                    </div><!-- /.col -->
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="/">admin</a></li>
                            <li class="breadcrumb-item"><a href="{{ route('admin.pages.index') }}">page</a></li>
                            <li class="breadcrumb-item active">edit page </li>
                        </ol>
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->

        <!-- Main content -->
        <div class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="card card-body">
                        <form action="{{ route('admin.pages.update', $page) }}"
                              method="post" enctype="multipart/form-data">
                            @method('PUT')
                           @include('admin.page.form')
                        </form>

                    </div>
                </div>
                <!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content -->
    </div>
@endsection
@section('js')
<script type="text/javascript">
    $(document).ready(function () {
        $('.ckeditor').ckeditor();
    });
</script>
@endsection

task/resources/views/admin/page/form.blade.php
@csrf

<div class="form-group">
    <label for="post_id"> post title</label>
    <select name="post_id" id="post_id" class="form-control">
        <option value>Not set</option>
        @foreach($posts as $post) 
            @if(isset($page))
                <option value="{{ $post->id }}" selected>{{ $post->title }}</option>
            @else
                <option value="{{ $post->id }}" >{{ $post->title }}</option>  
            @endif
        @endforeach
    </select>
    
</div>

<div class="form-group">
    <label for="titile">Title</label>
    <input type="text" name="title" id="name" class="form-control" value="{{ isset($page)?$page->title : '' }}">
    

</div>

<div class="form-group">
    <label for="img">img</label>
    <input type="file" name="img" id="img" class="form-control" 
    value="{{ isset($page)? $page->post->img : '' }}">
   

</div>


<div class="form-group">
<textarea class="ckeditor form-control" name="wysiwyg-editor">{!! isset($page)?$page->description : '' !!}</textarea>
   
</div>


<div class="text-center">
    <button type="submit" class="btn btn-success">Save</button>
</div>

task/resources/views/admin/page/index.blade.php
@extends('layouts.app')

@section('title', 'All Pages')

@section('content')
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0 text-dark">Pages</h1>
                    </div><!-- /.col -->
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="/">admin</a></li>
                            <li class="breadcrumb-item active">All Pages</li>
                        </ol>
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->

        <!-- Main content -->
        <div class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="card card-body">
                    <div class="row">
                            
                            <div class="col text-right">
                                <a href="{{ route('admin.pages.create') }}" class="btn btn-success">Create</a>
                            </div>
                        </div>
                        <table class="table table-bordered table-data mt-4">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Post_id</th>
                                    <th>Title</th>
                                    <th>post img</th>
                                    <th>date</th>
                                    <th>Description</th>
                                    <th>Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                            
                            </tbody>
                        </table>
                        
                    </div>
                </div>
        <!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
    <!-- /.content -->
    </div>
@endsection
@section('js')
    <script>

        $(function () {
            getAllClients();
        });

        $(document).on('click', '.delete', function (e) {
            Swal.fire({
                title: 'Are you sure?',
                text: "You won't be able to revert this!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, delete it!'
            }).then((result) => {
                if (result.isConfirmed) {
                    // $(`#delete-${$(this).data('id')}`).submit();
                    $.ajax({
                        url: $(this).data('url'),
                        type: 'POST',
                        data: {
                            _method : 'DELETE',
                            _token : '{{ csrf_token() }}'
                        },
                        success: function (res) {
                            if (result.value) {
                                Swal.fire(
                                    'Deleted!',
                                    'Your file has been deleted.',
                                    'success'
                                );

                                getAllClients();
                            }
                        }
                    });

                   
                }
            })
        });

      

        function getAllClients(page = 1) {
            $.ajax({
                url: '{{ route('admin.pages.get-pages') }}',
                type: 'GET',
                success: function (res) {
                    $('.table-data tbody').html(res);
                }
            })
        }
    </script>
@endsection

task/resources/views/admin/page/table.blade.php
@foreach($pages as $page)
    <tr>
        <td>{{ $page->id}}</td>                                   
        <td>
                                    
                                  
            
                                   
        </td>
        <td>{{ $page->title }}</td>
        <td> <img  style="width: 90px; height: 90px;" src="{{asset('images/posts/'.
             
        $page->img
      
         )}}" >
        </td>
        <td>
                                    
            {{ $page->created_at }}
                                    
        </td>
        <td>{!! $page->description !!}</td>
        <td>
                                    
            <a href="{{route('admin.pages.edit', $page)}}" class="btn btn-primary">Edit</a>
                                        
            <button type="button" class="btn btn-danger delete" data-url="{{ route('admin.pages.destroy', $page) }}">Delete</button>
        </td>
    </tr>
@endforeach
                          