task/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


    Route::get('/', 'Front\HomeController@showposts');
    Route::get('/pages', 'Front\HomeController@showpages')->name('pages');
    Route::get('/pagesdetails/{post}', 'Front\HomeController@showpages')->name('pagesdetails');

Route::group([
    'prefix' => '/admin',
    'as' => 'admin.',
    'middleware' => ['auth' ]
], function () {
Route::get('/', 'DashboardController')->name('dashboard');
     

//route users
Route::group([
    'prefix' => 'users',
    'as' => 'users.'
], function () {
    Route::get('/get-users', 'UserController@getUsers')->name('get-users');
});
Route::resource('/users', 'UserController');

//route posts

Route::group([
    'prefix' => 'posts',
    'as' => 'posts.'
], function () {
    Route::get('/get-posts', 'PostController@getPosts')->name('get-posts');
});
Route::resource('/posts', 'PostController');

//route pages

Route::group([
    'prefix' => 'pages',
    'as' => 'pages.'
], function () {
    Route::get('/get-pages', 'PageController@getPages')->name('get-pages');
});
Route::resource('/pages', 'PageController');

});




Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

task/app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','img'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
    public function post(){
        return $this->hasMany(Post::class);
    }
}

task/app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;
use App\User;
use App\Traits\UserTrait;
use Illuminate\Http\Request;

class UserController extends Controller
{
    use UserTrait;
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        return view('admin.user.index',[
            'users' => User::all()
            ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.user.create', [
            'users' => User::all()
        ]);
    }
    public function getUsers(Request $request)
    {
        return view('admin.user.table', [
            'users' => user::all()
        ]);
    }
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $file_name = $this->saveImage($request->file('img'),'images/users');
        $user = User::create([
            'name' => $request->name,
            'img'=> $file_name,
            'email'=> $request->email,
            'password'=> $request->password,
        ]);

        return redirect(route('admin.users.index', $user));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        return view('admin.user.edit', [
            'user' => $user,
            'users' => User::all()
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        $user->update($request->all());
        return redirect(route('admin.users.index', $user));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        $user->delete();
        return  redirect(route('admin.users.index'));
    }
}

task/resources/views/admin/user/create.blade.php
@extends('layouts.app')

@section('title', 'All Users')

@section('content')
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0 text-dark">users</h1>
                    </div><!-- /.col -->
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="/">admin</a></li>
                            <li class="breadcrumb-item"><a href="{{ route('admin.users.index') }}">users</a></li>
                            <li class="breadcrumb-item active">Create new user</li>
                        </ol>
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->

        <!-- Main content -->
        <div class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="card card-body">
                        <form action="{{ route('admin.users.store') }}" method="post" enctype="multipart/form-data">
                           @include('admin.user.form')
                        </form>

                    </div>
                </div>
                <!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content -->
    </div>
@endsection

task/resources/views/admin/user/edit.blade.php
@extends('layouts.app')

@section('title', 'All Users')

@section('content')
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0 text-dark">Users</h1>
                    </div><!-- /.col -->
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="/">admin</a></li>
                            <li class="breadcrumb-item"><a href="{{ route('admin.users.index') }}">user</a></li>
                            <li class="breadcrumb-item active">edit user </li>
                        </ol>
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->

        <!-- Main content -->
        <div class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="card card-body">
                        <form action="{{ route('admin.users.update', $user) }}"
                              method="post"  enctype="multipart/form-data">
                            @method('PUT')
                           @include('admin.user.form')
                        </form>

                    </div>
                </div>
                <!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content -->
    </div>
@endsection

task/resources/views/admin/user/form.blade.php
@csrf

<div class="form-group">
    <label for="name">Name</label>
    <input type="text" name="name" id="name" class="form-control" value="{{ isset($user)?$user->name : '' }}">
    

</div>
<div class="form-group">
    <label for="email">Email</label>
    <input type="text" name="email" id="email"  class="form-control" value="{{ isset($user)?$user->email : '' }}">
        
   
    
</div>
<div class="form-group">
    <label for="password">Password</label>
    <input type="password" name="password" id="password"  class="form-control" value="{{ isset($user)?$user->password: '' }}">
        
   
    
</div>
<div class="form-group">
    <label for="img">img</label>
    <input type="file" name="img" id="quntity" class="form-control" 
    value="{{ isset($user)?$user->img : '' }}">
   

</div>
<div class="text-center">
    <button type="submit" class="btn btn-success">Save</button>
</div>

task/resources/views/admin/user/index.blade.php
@extends('layouts.app')

@section('title', 'All Users')

@section('content')
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0 text-dark">Clients</h1>
                    </div><!-- /.col -->
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="/">admin</a></li>
                            <li class="breadcrumb-item active">All Users</li>
                        </ol>
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->

        <!-- Main content -->
        <div class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="card card-body">
                    <div class="row">
                            
                            <div class="col text-right">
                                <a href="{{ route('admin.users.create') }}" class="btn btn-success">Create</a>
                            </div>
                        </div>
                        <table class="table table-bordered table-data mt-4">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>name</th>
                                    <th>img</th>
                                    <th>Email</th>
                                    <th>Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                            
                            </tbody>
                        </table>
                        <div class="d-flex justify-content-end">
                            
                        </div>
                    </div>
                </div>
        <!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
    <!-- /.content -->
    </div>
@endsection
@section('js')
    <script>

        $(function () {
            getAllClients();
        });

        $(document).on('click', '.delete', function (e) {
            Swal.fire({
                title: 'Are you sure?',
                text: "You won't be able to revert this!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, delete it!'
            }).then((result) => {
                if (result.isConfirmed) {
                    // $(`#delete-${$(this).data('id')}`).submit();
                    $.ajax({
                        url: $(this).data('url'),
                        type: 'POST',
                        data: {
                            _method : 'DELETE',
                            _token : '{{ csrf_token() }}'
                        },
                        success: function (res) {
                            if (result.value) {
                                Swal.fire(
                                    'Deleted!',
                                    'Your file has been deleted.',
                                    'success'
                                );

                                getAllClients();
                            }
                        }
                    });

                   
                }
            })
        });

      

        function getAllClients(page = 1) {
            $.ajax({
                url: '{{ route('admin.users.get-users') }}',
                type: 'GET',
                success: function (res) {
                    $('.table-data tbody').html(res);
                }
            })
        }
    </script>
@endsection

task/resources/views/admin/user/table.blade.php
@foreach($users as $user)
                                <tr>
                                    <td>{{ $user->id }}</td>
                                    <td>{{ $user->name }}</td>
                                    <td><img  style="width: 90px; height: 90px;" src="{{asset('images/users/'.$user->img)}}"></td>
                                    <td>{{ $user->email }}</td>
                                    <td>
                                       
                                        <a href="{{route('admin.users.edit', $user)}}" class="btn btn-primary">Edit</a>
                                        
                                        <button type="button" class="btn btn-danger delete" data-url="{{ route('admin.users.destroy', $user) }}">Delete</button>
                                    </td>
                                </tr>
                            @endforeach
                          