task/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


    Route::get('/', 'Front\HomeController@showposts');
    Route::get('/pages', 'Front\HomeController@showpages')->name('pages');
    Route::get('/pagesdetails/{post}', 'Front\HomeController@showpages')->name('pagesdetails');

Route::group([
    'prefix' => '/admin',
    'as' => 'admin.',
    'middleware' => ['auth' ]
], function () {
Route::get('/', 'DashboardController')->name('dashboard');
     

//route users
Route::group([
    'prefix' => 'users',
    'as' => 'users.'
], function () {
    Route::get('/get-users', 'UserController@getUsers')->name('get-users');
});
Route::resource('/users', 'UserController');

//route posts

Route::group([
    'prefix' => 'posts',
    'as' => 'posts.'
], function () {
    Route::get('/get-posts', 'PostController@getPosts')->name('get-posts');
});
Route::resource('/posts', 'PostController');

//route pages

Route::group([
    'prefix' => 'pages',
    'as' => 'pages.'
], function () {
    Route::get('/get-pages', 'PageController@getPages')->name('get-pages');
});
Route::resource('/pages', 'PageController');

});




Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

task/app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    protected $fillable = [
        'title', 'img', 'description','user_id'
    ];
    public function user(){
        return $this->belongsTo(User::class ,'user_id');
    }
    public function page(){
        return $this->belongsTo(Page::class,'post_id');
    }
    public function latestPost()
{
    return $this->hasOne(Post::class)->latest();
}
}

task/app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;
use App\User;
use App\Post;
use App\Traits\PostTrait;
use Illuminate\Http\Request;

class PostController extends Controller
{
    use PostTrait;
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        return view('admin.post.index',[
            'posts' => Post::with(['user'])
            ]);
    }
    public function getPosts(Request $request)
    {
        return view('admin.post.table', [
            'posts' => Post::all()
        ]);
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.post.create', [
            'posts' => Post::all(),
            'users'=> User::all()
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $file_name = $this->saveImage($request->file('img'),'images/posts');
        $post = Post::create([
            'title' => $request->title,
            'img'=> $file_name,
            'description'=> $request->description,
            'user_id'=> $request->user_id
        ]);

        return redirect(route('admin.posts.index', $post));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function show(Post $post)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post)
    {
        return view('admin.post.edit', [
            'post' => $post,
            'posts' => Post::all(),
            'users'=> User::all()
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Post $post)
    {
        $post->update($request->all());
        return redirect(route('admin.posts.index', $post));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function destroy(Post $post)
    {
        $post->delete();
        return  redirect(route('admin.posts.index'));
    }
}

task/resources/views/admin/post/create.blade.php
@extends('layouts.app')

@section('title', 'All Posts')

@section('content')
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0 text-dark">posts</h1>
                    </div><!-- /.col -->
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="/">admin</a></li>
                            <li class="breadcrumb-item"><a href="{{ route('admin.posts.index') }}">posts</a></li>
                            <li class="breadcrumb-item active">Create new post</li>
                        </ol>
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->

        <!-- Main content -->
        <div class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="card card-body">
                        <form action="{{ route('admin.posts.store') }}" method="post" enctype="multipart/form-data">
                           @include('admin.post.form')
                        </form>

                    </div>
                </div>
                <!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content -->
    </div>
@endsection

task/resources/views/admin/post/edit.blade.php
@extends('layouts.app')

@section('title', 'All Posts')

@section('content')
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0 text-dark">Posts</h1>
                    </div><!-- /.col -->
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="/">admin</a></li>
                            <li class="breadcrumb-item"><a href="{{ route('admin.posts.index') }}">post</a></li>
                            <li class="breadcrumb-item active">edit post </li>
                        </ol>
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->

        <!-- Main content -->
        <div class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="card card-body">
                        <form action="{{ route('admin.posts.update', $post) }}"
                              method="post" enctype="multipart/form-data">
                            @method('PUT')
                           @include('admin.post.form')
                        </form>

                    </div>
                </div>
                <!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content -->
    </div>
@endsection
@section('js')
<script type="text/javascript">
    $(document).ready(function () {
        $('.ckeditor').ckeditor();
    });
</script>
@endsection

task/resources/views/admin/post/form.blade.php
@csrf
<div class="form-group">
    <label for="user_id"> User name</label>
    <select name="user_id" id="user_id" class="form-control">
        <option value>Not set</option>
        @foreach($users as $user) 
            @if(isset($post))
                <option value="{{ $user->id }}" selected>{{ $user->name }}</option>
            @else
                <option value="{{ $user->id }}" >{{ $user->name }}</option>  
            @endif
        @endforeach
    </select>
    
</div>

<div class="form-group">
    <label for="titile">Title</label>
    <input type="text" name="title" id="name" class="form-control" value="{{ isset($post)?$post->title : '' }}">
    

</div>

<div class="form-group">
    <label for="img">img</label>
    <input type="file" name="img" id="quntity" class="form-control" 
    value="{{ isset($post)? $post->img : '' }}">
   

</div>


<div class="form-group">
<textarea class="ckeditor form-control" name="wysiwyg-editor">{!! isset($post)?$post->description : '' !!}</textarea>
   
</div>



<div class="text-center">
    <button type="submit" class="btn btn-success">Save</button>
</div>

task/resources/views/admin/post/index.blade.php
@extends('layouts.app')

@section('title', 'All Posts')

@section('content')
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0 text-dark">POSTS</h1>
                    </div><!-- /.col -->
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="/">admin</a></li>
                            <li class="breadcrumb-item active">All Posts</li>
                        </ol>
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->

        <!-- Main content -->
        <div class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="card card-body">
                    <div class="row">
                            
                            <div class="col text-right">
                                <a href="{{ route('admin.posts.create') }}" class="btn btn-success">Create</a>
                            </div>
                        </div>
                        <table class="table table-bordered table-data mt-4">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>user_id</th>
                                    <th>title</th>
                                    <th>img</th>
                                    <th>description</th>
                                    <th>Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                            
                            </tbody>
                        </table>
                        
                    </div>
                </div>
        <!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
    <!-- /.content -->
    </div>
@endsection
@section('js')
    <script>

        $(function () {
            getAllClients();
        });

        $(document).on('click', '.delete', function (e) {
            Swal.fire({
                title: 'Are you sure?',
                text: "You won't be able to revert this!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, delete it!'
            }).then((result) => {
                if (result.isConfirmed) {
                    // $(`#delete-${$(this).data('id')}`).submit();
                    $.ajax({
                        url: $(this).data('url'),
                        type: 'POST',
                        data: {
                            _method : 'DELETE',
                            _token : '{{ csrf_token() }}'
                        },
                        success: function (res) {
                            if (result.value) {
                                Swal.fire(
                                    'Deleted!',
                                    'Your file has been deleted.',
                                    'success'
                                );

                                getAllClients();
                            }
                        }
                    });

                   
                }
            })
        });

      

        function getAllClients(page = 1) {
            $.ajax({
                url: '{{ route('admin.posts.get-posts') }}',
                type: 'GET',
                success: function (res) {
                    $('.table-data tbody').html(res);
                }
            })
        }
    </script>
@endsection

task/resources/views/admin/post/table.blade.php
@foreach($posts as $post)
    <tr>
        <td>{{ $post->id }}</td>
        <td>
            @if ($post->user)
                {{ $post->user->name }}
            @endif
        </td>
        <td>{{ $post->title }}</td>
        <td><img  style="width: 90px; height: 90px;" src="{{asset('images/posts/'.$post->img)}}"></td>
        <td>{!! $post->description !!}</td>
        <td>
            
            <a href="{{route('admin.posts.edit', $post)}}" class="btn btn-primary">Edit</a>
                                        
            <button type="button" class="btn btn-danger delete" data-url="{{ route('admin.posts.destroy', $post) }}">Delete</button>
        </td>
    </tr>
@endforeach
                          